services:
  - type: web
    name: aegis-ai-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn index:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ETHERSCAN_API_KEY
        sync: false
      - key: BASESCAN_API_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_FROM_EMAIL
        sync: false
      - key: CDP_API_KEY_NAME
        sync: false
      - key: CDP_API_KEY_PRIVATE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
